### PR TITLE
Update Infotext.php

### PR DESCRIPTION
**Pull request by stijnbernards**
Paazl widget config second argument is the storeview not the scope type

### CODE REVIEW

**Comment by Marvin-Magmodules** [comment]
@stijnbernards thnx for the PR, merged into 1.6.1 release

**Comment by stijnbernards** [comment]
Hey @Marvin-Magmodules cheers! It seems like the PR is closed not merged, was this intentional? :)

**Comment by Marvin-Magmodules** [comment]
Hi @stijnbernards, yes it has been merged; https://github.com/Paazl/magento2-checkout-widget/compare/1.6.0...master

**Comment by stijnbernards** [comment]
Ah lol, noice 👌 Have a good weekend :)

**Pull request closed without merging**
